services:
  - type: web
    name: vehicle-maintenance-tracker
    env: python
    plan: free
    buildCommand: |
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r requirements.txt
    startCommand: python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18
      - key: ENVIRONMENT
        value: production
